language: python
python:
    - "pypy"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install .
    - pip install nose coverage
before_script: mkdir -p shippable/testresults
script:
    - nosetests --with-coverage --cover-package=limelight --with-xunit --xunit-file=shippable/testresults/nosetests.xml
    - coverage xml -o shippable/codecoverage/coverage.xml